# Generated by Django 6.0.3 on 2026-03-26 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('menu', 'Menu Principal'), ('aguardando_valor_gasto', 'Aguardando Valor do Gasto'), ('aguardando_categoria_gasto', 'Aguardando Categoria do Gasto'), ('confirmando_gasto', 'Confirmando Gasto'), ('aguardando_valor_entrada', 'Aguardando Valor da Entrada'), ('aguardando_fonte_entrada', 'Aguardando Fonte da Entrada'), ('confirmando_entrada', 'Confirmando Entrada')], default='menu', max_length=50)),
                ('dados_temporarios', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_conversa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Conversa',
                'verbose_name_plural': 'Sessões de Conversa',
            },
        ),
    ]
