# Generated by Django 6.0.3 on 2026-04-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoconversa',
            name='estado',
            field=models.CharField(choices=[('menu', 'Menu Principal'), ('aguardando_valor_gasto', 'Aguardando Valor do Gasto'), ('aguardando_categoria_gasto', 'Aguardando Categoria do Gasto'), ('confirmando_gasto', 'Confirmando Gasto'), ('aguardando_valor_entrada', 'Aguardando Valor da Entrada'), ('aguardando_fonte_entrada', 'Aguardando Fonte da Entrada'), ('confirmando_entrada', 'Confirmando Entrada'), ('listando_gastos', 'Listando Gastos'), ('listando_entradas', 'Listando Entradas'), ('confirmando_exclusao_gasto', 'Confirmando Exclusão de Gasto'), ('confirmando_exclusao_entrada', 'Confirmando Exclusão de Entrada'), ('editando_gasto_campo', 'Escolhendo Campo do Gasto'), ('editando_gasto_valor', 'Editando Valor do Gasto'), ('editando_gasto_categoria', 'Editando Categoria do Gasto'), ('editando_entrada_campo', 'Escolhendo Campo da Entrada'), ('editando_entrada_valor', 'Editando Valor da Entrada'), ('editando_entrada_fonte', 'Editando Fonte da Entrada')], default='menu', max_length=50),
        ),
    ]
