# Generated by Django 6.0.3 on 2026-03-25 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_log_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('origem', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('mobile', 'Mobile'), ('api', 'API')], default='api', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('dispositivo', models.CharField(blank=True, default='', max_length=20)),
                ('duracao_ms', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-criado_em'],
            },
        ),
    ]
