# Generated by Django 6.0.3 on 2026-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_log_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='hash_integridade',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('criado', 'Criado'), ('atualizado', 'Atualizado'), ('deletado', 'Deletado'), ('bulk_deletado', 'Bulk Deletado'), ('bulk_atualizado', 'Bulk Atualizado')], max_length=20),
        ),
    ]
