# Generated by Django 6.0.3 on 2026-04-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_hash_integridade_log_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
