# Generated by Django 6.0.3 on 2026-04-03 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_entrada_atualizado_em_gasto_atualizado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['usuario', 'data'], name='idx_entrada_usuario_data'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['usuario', 'fonte', 'data'], name='idx_entrada_usuario_fonte_data'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['usuario', 'data'], name='idx_gasto_usuario_data'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['usuario', 'categoria', 'data'], name='idx_gasto_usuario_categoria_data'),
        ),
    ]
